### ISSUE TITLE
grid_search function returning error as cv_space data frame is empty ?

### ISSUE THREAD

**Issue by ghost** [mabrek/kaggle-rossman-store-sales#1]
@mabrek I was trying to run the scripts and learn from them. Great scripts. I have already learnt a lot. But I am stuck at one point.

In playground.R I am getting the below error.

`Error in elnet(x, is.sparse, ix, jx, y, weights, offset, type.gaussian,  : 
  NA/NaN/Inf in foreign function call (arg 5)
In addition: Warning message:
In elnet(x, is.sparse, ix, jx, y, weights, offset, type.gaussian,  :
  NAs introduced by coercion`

I think it's because of the below code cv_space is getting empty.

`cv_space <- select_(space,
                      .dots = c("-promo_after", "-promo2_after",
                                "-holiday_b_before", "-holiday_c_before",
                                "-holiday_c_after"))`

Please suggest.

**Comment by ghost** [comment]
How do i assign this to @mabrek  ?

**Comment by mabrek** [comment]
playground.R is just a bunch of almost unrelated code snippets never intended to be run one after another.
The only insight from the grid_search function was to stick to  alpha=1 which were hardcoded after that.

**Comment by ghost** [comment]
@mabrek I thought playground script has the modeling part. Data script has feature engineering part. Where do I find the modeling aprt?

P.S.: I am new to GitHub so excuse me If I don't know GitHub Etiquette.

**Comment by mabrek** [comment]
These are modeling parts used for submissions
https://github.com/mabrek/kaggle-rossman-store-sales/blob/master/R/playground.R#L111
https://github.com/mabrek/kaggle-rossman-store-sales/blob/master/R/playground.R#L236
https://github.com/mabrek/kaggle-rossman-store-sales/blob/master/R/playground.R#L151

**Comment by ghost** [comment]
@mabrek wonderful, thanks a lot.
